version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped
    environment:
      - NODE_ENV=production
